openapi: 3.0.1
info:
  title: API de Envíos
  version: 1.0.0
  description: API REST para registrar y consultar envíos.
paths:
  /envios:
    get:
      summary: Listar todos los envíos
      responses:
        "200":
          description: Lista de envíos
    post:
      summary: Crear un nuevo envío
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Envio"
      responses:
        "201":
          description: Envío creado
  /envios/{id}:
    get:
      summary: Obtener un envío por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detalle del envío
components:
  schemas:
    Envio:
      type: object
      properties:
        id:
          type: string
        cliente:
          type: string
        direccion:
          type: string
        estado:
          type: string
